### ISSUE TITLE
Select methods not returning anything (void)

### ISSUE THREAD

**Issue by lavgup** [siddharthvp/mwn#22]
Hi,

There seems to be an issue with the `mwn` class consisting of some methods that return `void` or `Promise#void` when they should in fact return data from the API. An example of this is `mwn#getSiteInfo`, which returns void since it's not returning the result of `Title.processNamepsaceData` (which is also returning void).

See `mwn#getSiteInfo`'s code:
```ts
getSiteInfo(): Promise<void> {
    return this.request({
        action: 'query',
        meta: 'siteinfo',
        siprop: 'general|namespaces|namespacealiases',
    }).then((result) => {
        // Title.processNamespaceData should have a return statement
        // should also be a return statement here
        this.title.processNamespaceData(result);
    });
}
```

You could also just use `.then(this.title.processNamespaceData)` for more concise syntax. 

Types may also need to be adjusted to suit any changes. Please let me if I am misunderstanding the usage of this function.

**Comment by siddharthvp** [comment]
`getSiteInfo` is only intended for internal purposes - populating the site data in the bot object to allow for parsing of titles, so the void return is intentional.

For fetching site data for other purposes, you can do `bot.query({ meta: 'siteinfo', siprop: ... })`.

**Comment by lavgup** [comment]
Alright, thanks for letting me know.
