### ISSUE TITLE
Typo in user rights

### ISSUE THREAD

**Issue by Dr4goniez** [siddharthvp/mwn#52]
Thanks for the great library. I just noticed that there's a typo in [bot.ts#L750](https://github.com/siddharthvp/mwn/blob/ccc6fb8/src/bot.ts#L750): it's "[apihighlimit**s**](https://meta.wikimedia.org/wiki/Special:GlobalGroupPermissions)", not "apihighlimit", without "s". I was wondering why bot.hasApiHighLimit always returns false even though my bot has a bot flag, but this seems to be the cause.

**Comment by siddharthvp** [comment]
Fixed in e20d7bd5, thanks for pointing it out!
