### ISSUE TITLE
version 2?

### ISSUE THREAD

**Issue by postylem** [siddharthvp/mwn#62]
New user, bit confused.  Is there a version 2 release?
In the [getting started guide](https://mwn.toolforge.org/docs/getting-started) it says:

> Prior to mwn v2.0.0, import was via const { mwn } = require('mwn'). Prior to v0.8.0, it was via const mwn = require('mwn');

But the latest release as of writing is [1.11.5](https://github.com/siddharthvp/mwn/releases/tag/1.11.5).  Is this a typo? I'm confused.

**Comment by siddharthvp** [comment]
Hi. The latest version in master branch is v2.0.0. But the latest released version is still 1.11.5.

I'll get to around to releasing the v2 soon.

**Comment by siddharthvp** [comment]
v2.0.0 is released now!

**Comment by postylem** [comment]
Oh wow, that was fast.
