### ISSUE TITLE
Parsing sections of empty text

### ISSUE THREAD

**Issue by smigles** [siddharthvp/mwn#65]
Now `new Mwn().Wikitext.parseSections('')` (empty text) returns one element with empty content string:

```js
[
    {
        level: 1,
        header: null,
        index: 0,
        content: ''
    }
]
```

I think `parseSections('')` must returns the empty array or `null`.

**Comment by siddharthvp** [comment]
I think this is the correct behaviour. Every page, even an empty page, has a section 0 which is the top content before the first section header.

**Comment by smigles** [comment]
An empty page has no content, so I think it shouldn't have any section at all. A section with empty `content` is redundant. But if you did this intentionally, I will not insist.
