### ISSUE TITLE
`maxlagPause` option is missing

### ISSUE THREAD

**Issue by smigles** [siddharthvp/mwn#68]
The `maxlagPause` option is missing in the `MwnOptions` object.

https://github.com/siddharthvp/mwn/blob/e3500dc32f3096e7ea43117da6608c23baa2072b/README.md?plain=1#L35

Maybe you meant the `retryPause` option?

https://github.com/siddharthvp/mwn/blob/2437b3835f745f6b094ef7acb1c3e46ad5e808bd/src/bot.ts#L109

**Comment by siddharthvp** [comment]
Yes. Thanks for catching it! Fixed in 60959cda.
