### ISSUE TITLE
Template only exported as type

### ISSUE THREAD

**Issue by JN-Jones** [siddharthvp/mwn#79]
Hi, in certain scenarios I'd like to create an instance of `Template` directly. One such scenario are tests for wiki-specific functionality that relies on `Template`. As it is part of the [documentation](https://mwn.toolforge.org/docs/api/classes/template.html) I expected this to work, however it currently is only exported as type so I've to rely on a workaround that requires me to setup a proper bot instance.

```ts
const wt = new bot.Wikitext("{{template}}");
wt.parseTemplates({});
const template = wt.templates[0];
```

**Comment by siddharthvp** [comment]
Fixed in 870ddd153.
