### ISSUE TITLE
[question] how I am supposed to do cargo queries ?

### ISSUE THREAD

**Issue by Evileoo** [siddharthvp/mwn#82]
Hello, I'd like to do a cargo query to a fandom.
Here is the query : `https://lol.fandom.com/api.php?action=cargoquery&tables=Tournaments&fields=Tournaments.Name,Tournaments.OverviewPage`

I have no clue on how to do it with any MediaWiki js api
As this is the latest updated one I'm seeking for help here

Nothing found on internet

Do someone know how to do it ?

**Comment by siddharthvp** [comment]
There's no helper function to do a cargo query, but you can use the `request()` method directly:

```js
const bot = new Mwn({ apiUrl: 'https://lol.fandom.com/api.php' })
await bot.request({ 
  action: 'cargoquery', 
  tables: 'Tournaments', 
  fields: 'Tournaments.Name,Tournaments.OverviewPage' 
})
```

**Comment by Evileoo** [comment]
omg thank you
I spent so much time in order to make it work
